name: Build ESP32-C3 Mochi Firmware

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SKETCH: mochi

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 board core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install common libraries
        run: |
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit SSD1306"
          arduino-cli lib install "Adafruit BusIO"
          arduino-cli lib install "U8g2"

      - name: Compile firmware
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32c3 \
            --output-dir build \
            "$SKETCH"

      - name: Show build files
        run: ls -lah build

      - name: Upload firmware files
        uses: actions/upload-artifact@v4
        with:
          name: esp32c3-mochi-firmware
          path: build/*
